sectors:

  # Represents a group of sectors
  survival:
    su1:
      region:
        a:
          x: 0.0
          y: 100.0
        b:
          x: 50.0
          y: 50.0

    su2:
      region:
        a:
          x: 50.0
          y: 0.0
        b:
          x: 100.0
          y: 0.0